# Generated by Django 6.0.2 on 2026-02-18 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('recieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
