# Generated by Django 6.0.2 on 2026-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/avatars/avatar.jpg', upload_to='accounts/avatars'),
        ),
    ]
