# Generated by Django 6.0.2 on 2026-02-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/avatars/avatar.png', upload_to='accounts/avatars'),
        ),
    ]
