# Generated by Django 6.0.2 on 2026-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='series/thumbnails'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(upload_to='series/poster'),
        ),
    ]
