# Generated by Django 6.0.2 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_thumbnail_alter_series_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='post_type',
            field=models.CharField(blank=True, default='series'),
        ),
    ]
