# Generated by Django 6.0.2 on 2026-03-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='post_type',
            new_name='category',
        ),
    ]
