# Generated by Django 6.0.2 on 2026-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('news', 'News'), ('leaks', 'Leak'), ('did_you_know', 'Did You Know'), ('behind_scenes', 'Behind Scenes')], max_length=30),
        ),
    ]
