# Generated by Django 6.0.2 on 2026-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_create_date_alter_contentblock_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('stories', 'Stories'), ('facts', 'Facts'), ('leaks', 'Leaks')], max_length=30, null=True),
        ),
    ]
