# Generated by Django 6.0.2 on 2026-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
