# Generated by Django 6.0.2 on 2026-02-16 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('photo', models.ImageField(upload_to='actors/')),
                ('thumbnail', models.ImageField(upload_to='actors/thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(upload_to='movies/posters')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movies/thumbnails')),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('rating', models.FloatField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ManyToManyField(related_name='movie_casts', to='movies.actor')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
