# Generated by Django 6.0.2 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_bio_alter_actor_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='post_type',
            field=models.CharField(blank=True, default='movie'),
        ),
    ]
