# Generated by Django 6.0.2 on 2026-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_post_type_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, default='movies'),
        ),
    ]
